try {
    doIt();
    console.log('Success');
}
catch ( error ) {
    console.log('Fail');
}
finally {
    console.log('Finally!');
}

// function doIt() {}